### ISSUE TITLE
[Error] 503 Server Error: Service Temporarily Unavailable for url: 

### ISSUE THREAD

**Issue by chrisfry** [MISP/MISP-maltego#1]
Getting this 503 error using maltego, any pointers where one can look for troubleshooting info?

**Comment by melegar** [comment]
I had this error with other MISP searches.  Its likely a timeout on your apache client hosting MISP.  You can extend this timeout in httpd.conf for your apache server.  Be sure to restart apache afterwards.

**Comment by adulau** [comment]
misp-maltego has been rewritten completely. Could you test the latest version? And reopen the issue if the problem still exists. Thank you very much.
