### ISSUE TITLE
Cannot run program "/usr/local/bin/dispatcher" (in directory "\root\MISP-maltego\src")

### ISSUE THREAD

**Issue by ghost** [MISP/MISP-maltego#16]
When running from Maltego Classic on Windows 10 I get the following error after installation when running a transform:

Error running local transform: java.io.IOException: Cannot run program "/usr/local/bin/dispatcher" (in directory "\root\MISP-maltego\src"): CreateProcess error=2, The system cannot find the file specified (from entity "0")

Installed Python3.5.

**Comment by cvandeplas** [comment]
Hi Matt, can you share how you fixed this? 
I am not aware of many Windows users of MISP-maltego, and honestly am not sure it will work right now, so any feedback is definitely welcome !!  I'll do my best to fix the issues to ensure it also works with Windows.

**Comment by syloktools** [comment]
I am trying to use it on Windows as well. Having issues the same as above.
