### ISSUE TITLE
Error message: No module named MISP_maltego

### ISSUE THREAD

**Issue by mkatani** [MISP/MISP-maltego#20]
I am trying to install the package in my MISP instance regarding to the tutorial available here.
After installing MISP-maltego, i tried to generate the Maltego bundle with canari command.
After running the command i recieve following error message:

```
Loading Canari configuration file '/home/misp/.canari/canari.conf'
Usage: canari create-profile [OPTIONS] [PACKAGE]

Error: Invalid value for "[PACKAGE]": Does not appear to be a valid canari package. Couldn't import the 'MISP_maltego' module in 'MISP_maltego'. Error message: No module named MISP_maltego
```
I can not find any solution for this error, can you please advice me how i can do this step?
 
Thanks

**Comment by cvandeplas** [comment]
Which OS/distribution are you using? 
Can you please run the following and give the ouput?
```
pip3 list | fgrep -e MISP -e canari
```

**Comment by mkatani** [comment]
OS/distribution: Ubuntu 18.04.3 LTS
here the output of the command:
canari (3.3.10)
MISP-maltego (1.3.7)

Thanks

**Comment by cvandeplas** [comment]
I think I might have a clue. 
Did you install it as user or globally? 
To list the packages **as user** run:
```
pip3 list --user | fgrep -e MISP -e canari
```

If this outputs canari and MISP-maltego, try to remove the packages:
- either ALL user-level installed ones (dependencies and so), `rm -Rf $HOME/.local/lib/python3.6`
- or only the relevant ones (as user) `pip3 uninstall canari MISP-maltego`

Then install MISP-maltego again as root, and ask canari to generate the Maltego package as user:
```
sudo pip3 install MISP-maltego
canari create-profile MISP_maltego
```

**Comment by mkatani** [comment]
Great many many thanks for the help, now it works fine :)

**Comment by cvandeplas** [comment]
great, I've already changed the documentation to include the "sudo" part with pip3. The cause might have been that some modules were probably installed on user level, and others on system level, which for a weird reason caused python/canari not to find the MISP_maltego code.
