### ISSUE TITLE
Error while running local transform

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP-maltego#22]
Hey,

I got the following error when running a local transform :

> Transform Event To All returned with an error: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/canari/maltego/runner.py", line 130, in local_transform_runner
    config
  File "/usr/local/lib/python3.7/dist-packages/MISP_maltego/transforms/eventtoattributes.py", line 94, in do_transform
    if super().do_transform(request, response, config):
  File "/usr/local/lib/python3.7/dist-packages/MISP_maltego/transforms/eventtoattributes.py", line 42, in do_transform
    search_result = self.misp.search(controller='events', eventid=event_id, with_attachments=False)
AttributeError: 'NoneType' object has no attribute 'search' (from entity "57588")

**Comment by cvandeplas** [comment]
This will likely be because of your MISP connection that was not established correctly. This should return an [error message](https://github.com/MISP/MISP-maltego/blob/master/src/MISP_maltego/transforms/common/util.py#L193), but it seems it doesn't.

Can you verify your $HOME/.canari/MISP_maltego.conf file and double check the `misp_url` and `misp_key` ?

**Comment by FafnerKeyZee** [comment]
I have this:

> [MISP_maltego.local]
misp_url = https://10.0.XX.YYY/
misp_key = Y..REMOVED..K
misp_verify = False
misp_debug = False
check_updates = True
[MISP_maltego.remote]

**Comment by cvandeplas** [comment]
Fixed in 3e37cdf845573ab57f9428b78c19dfc32414a362 and v1.4.3

**Comment by FafnerKeyZee** [comment]
Yep, working like a charm.

Thanks a lot :)

**Comment by cyberpewpewpew** [comment]
Hi, I'm experiencing the same issue. "Cannot connect to MISP server"

Currently on v1.4.3, MISP URL and API key has been entered in MIS__maltego.conf. Able to ping MISP interface as well.
