### ISSUE TITLE
Allow wildcard prefix/suffix search for attribute types

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP-maltego#28]
Allow wildcard searches, as suffix or as prefix, for some attribute types.
Examples:
- %.domain.com for domain
- %.domain.com% for domain
- subodmain.domain.com% for URL
etc...

This could also allow cross-attribute type pivoting (evil.com stored as domain and pivoted to %@%evil.com emails); which could be very interesting in a Maltego machine.

**Comment by cvandeplas** [comment]
I believe this is now implemented in v1.4.5 and commit a1ba3890ebea064cef8a0794b5fc9d7331a3bebb
Note that wildcards are only supported at the front/end and not within. This is a limitation of MISP.
