### ISSUE TITLE
Unable to run event2ip attribute

### ISSUE THREAD

**Issue by jimbolya0607** [MISP/MISP-maltego#3]
/usr/local/lib/python2.7/dist-packages/pymisp/api.py:20: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
/usr/local/lib/python2.7/dist-packages/pymisp/mispevent.py:45: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
/usr/local/lib/python2.7/dist-packages/pymisp/api.py:39: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "misp_event2ip.py", line 37, in <module>
    mt.addUIMessage("[ERROR]  " + str(e))
NameError: name 'mt' is not defined

python --version
Python 2.7.12

python3 --version
Python 3.5.2

If i put in an IP or set of IPs i can search for the associated event.  However, after the event(s) have been returned and I want to see all of the IPs in that event I get the above error.  I've tried different file associations in the transform configuration and whatnot.  Nothing seems to resolve this. 

Jimbo

**Comment by adulau** [comment]
misp-maltego has been rewritten completely. Could you test the latest version? And reopen the issue if the problem still exists. Thank you very much.
