### ISSUE TITLE
nginx returns a 504 gateway timeout before pymisp timeouts when the MISP server is not accessible remotely

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP-maltego#31]
This is probably because pymisp timeouts are longer than nginx timeouts (when connecting to the MISP instance).
This results in an error that does not help the user.

TODO: investigate and fix (add timeout on initial pymisp connection or change timeouts in nginx reverse proxy)

**Comment by cvandeplas** [comment]
Fixed in https://github.com/MISP/PyMISP/pull/585 
Waiting for PR to be merged and new release to be published.
I might patch the server manually though.

**Comment by Rafiot** [comment]
(merged)

... or you prefer to keep it open until the new release?

**Comment by cvandeplas** [comment]
TODO for me: close this and bump version once pymisp has released the new version.

Also merge the fix-timeout branch
