### ISSUE TITLE
performance issue with Search in MISP

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP-maltego#35]
> For reference, I’m accessing the https://covid-19.iglocska.eu/ community. I tried running a few simple wildcard searches to pull in relevant events, which seem to always result in 504 errors. For instance, I tried running both “Search in MISP” and “To MISP Events” from a Phrase entity with the value “n95%“. 
This yields search results pretty quickly on the web version of the community). 

In this case, this [code](https://github.com/MISP/MISP-maltego/blob/master/src/MISP_maltego/transforms/attributetoevent.py#L85) is the one doing the search, so using the PyMISP search() function to do a remote search on the (covid-19) MISP instance. 

It is possible that some quirks on PyMISP level or MISP level cause a slow response when searching through the API.
A quick check confirms, in pymisp this is terribly slow:
```python
misp = PyMISP('https://covid-19.iglocska.eu/', 'mykey')
r = misp.search(controller='events', value='n95%', with_attachments=False)
```

This needs to be researched further:
- what is sent to MISP
- is PyMISP or MISP at fault?

**Comment by cvandeplas** [comment]
Further discussions about this are that this leads full events to be pulled.
So that's a LOT of data/backend work.

A better implementation could be to change the implementation to an `controller="attribute΅` search, and then do the magic that's needed to make the rest of the code also work.

**Comment by cvandeplas** [comment]
Taking care of "why did I choose to use the events controller as return object" ? I'm not sure anymore, but there must have been a reason to do so.

**Comment by cvandeplas** [comment]
The reason was that if we do a `controller=attribute` we don't have the object info and cannot build our object. 
When implementing `controller=object` I stumbled on [a bug](https://github.com/MISP/MISP/issues/6016).  So the current implementation now only returns attributes.

**Comment by iglocska** [comment]
The bug should now be resolved, so feel free to re-add objects.
