### ISSUE TITLE
Proxy issue: Traceback with merge_environment_settings

### ISSUE THREAD

**Issue by andurin** [MISP/MISP-maltego#39]
I'm stuck with a strange python requests/session issue using MISP-maltego on a clean environment.

This installation doesn't need a proxy to reach my misp instance and curl is just running fine. No "*proxy*" environment variables set.
Did someone see that before?

```
Traceback (most recent call last):
  File "/opt/maltego-venv/lib/python3.7/site-packages/pymisp/api.py", line 119, in __init__
    response = self.recommended_pymisp_version
  File "/opt/maltego-venv/lib/python3.7/site-packages/pymisp/api.py", line 175, in recommended_pymisp_version
    response = self._prepare_request('GET', 'servers/getPyMISPVersion.json')
  File "/opt/maltego-venv/lib/python3.7/site-packages/pymisp/api.py", line 2362, in _prepare_request
    settings = s.merge_environment_settings(req.url, proxies=self.proxies or {}, stream=None, verify=self.ssl, cert=self.cert)
  File "/opt/maltego-venv/lib/python3.7/site-packages/requests/sessions.py", line 698, in merge_environment_settings
    no_proxy = proxies.get('no_proxy') if proxies is not None else None
AttributeError: 'bool' object has no attribute 'get'
```

**Comment by cvandeplas** [comment]
That's weird. 
What is the proxy configuration of your maltego?  (I would expect Maltego could set env variables to the scripts it runs)

**Comment by andurin** [comment]
"use system default" and even on "No Proxy" same error.

**Comment by andurin** [comment]
Curios... 

requests/session.py:698:
`            no_proxy = proxies.get('no_proxy') if proxies is not None else None`

against:
pymisp/api.py
`    settings = s.merge_environment_settings(req.url, proxies=self.proxies or {}, stream=None, verify=self.ssl, cert=self.cert)`

Is it a conflict between pymisp sets an empty dict() and requests/session tried to get on that dict since it is not None?

**Comment by cvandeplas** [comment]
nice catch !!!  although it works on my side
what is the version of all your libs? requests/pymisp?
Is pymisp working standalone? 
Try in `ipython3`
```python
from pymisp import PyMISP
misp = PyMISP(url='yoururl', key='yourapikey')
```

**Comment by andurin** [comment]
Versions:
```
pymisp             2.4.128
requests           2.24.0
```

hm.. may it be sourced in the way misp-maltego does the init()? misp-maltego uses more postional args that I normally used to... let me cross check.

**Comment by andurin** [comment]
Update: It's an issue with the positional params:

`# self.misp = PyMISP(misp_url, misp_key, misp_verify, 'json', misp_debug, tool='misp_maltego', timeout=(2, 60))
            self.misp = PyMISP(misp_url, misp_key, misp_verify, debug=misp_debug, tool='misp_maltego', timeout=(2, 60))
`

Actual pymisp doesn't care about output format wishes so i removed the `json` and clarified `debug=`.

Working now.

Edit: If it makes sense to you - would you change it on your own? IMO It's to small for a PR....

**Comment by cvandeplas** [comment]
Nice catch, thanks. It should be fixed now. Can you confirm?
It must indeed be something of the a recent PyMISP version.

**Comment by andurin** [comment]
> Nice catch, thanks. It should be fixed now. Can you confirm?

Confirmed - changed that line manually and Connections works like a charm.
Thank you for your time and the final fix.
