### ISSUE TITLE
Limiting transforms depending of PAP or TLP classification of a MISP event

### ISSUE THREAD

**Issue by adulau** [MISP/MISP-maltego#4]
Limiting transforms depending of PAP or TLP classification of a MISP event as discussed during the session.

**Comment by cvandeplas** [comment]
While I'm still looking for something similar blocking as Cortex does, here are some ideas:

- [Bookmarks](http://www.canariproject.com/en/latest/canari.maltego.message.html#canari.maltego.message.Entity.bookmark): add a colored star on top of the entity. 
  - good: maps easily to TLP or PAP separately
  - bad: has no white color, does not support to separately TLP/PAP
![image](https://user-images.githubusercontent.com/1073662/49803103-33e9bc80-fd4f-11e8-82ae-42e966dde14d.png)

- [Notes](http://www.canariproject.com/en/latest/canari.maltego.message.html#canari.maltego.message.Entity.notes): A string containing additional notes that can be attached to a Maltego entity. 
![image](https://user-images.githubusercontent.com/1073662/49803150-52e84e80-fd4f-11e8-9de9-467b0139caee.png)


As notes:
- inherit tags from the event 
- an attribute should have the lowest level of TLP/PAP: for example, if something is TLP:White or Green the chose needs to be White.

**Comment by cvandeplas** [comment]
A first implementation is found in commit 0790c53. 
Tags from a specific type will be added as note to an `Entity`, the currently implemented ones are : `['tlp:', 'PAP:', 'de-vs:', 'euci:', 'fr-classif:', 'nato:']`

![image](https://user-images.githubusercontent.com/1073662/49808019-cbeda300-fd5b-11e8-9d10-a638b61c5f6e.png)

**Comment by cvandeplas** [comment]
I will close this issue, as limiting other (non-MISP-maltego) transforms is not technically possible with Maltego. The current implementation is the best we can do and give the analyst an idea of what can be done or not.
