### ISSUE TITLE
MISP ask for URL and Server on Maltego

### ISSUE THREAD

**Issue by kairosart** [MISP/MISP-maltego#42]
ATT&CK transforms do not require a MISP server or API key to be configured." according to https://github.com/MISP/MISP-maltego.

But I'm trying to do an example on Maltego CE and a pop up window asks me for URL and Server.

Steps:

1. Add a Mail entity.
2. Use the "To MISP events" transform.

Result:

![image](https://user-images.githubusercontent.com/6544570/93063269-4c021480-f676-11ea-9e42-afdbea803e7e.png)

Any idea?

**Comment by cvandeplas** [comment]
Hi,
As explained on the project page:
- ATT&CK transforms do not require a MISP server or API key to be configured.
- MISP transforms require having access to a MISP Threat Sharing server / community. You can run your own instance (and add your data to it) or join an existing community.

Reach out to your local cyber security communities, as they might already have a MISP Threat Sharing instance up'n'running that you might be able to access.Alternatively here is a (short) list of some communities: https://www.misp-project.org/communities/

Regards
