### ISSUE TITLE
MISP-Maltego locally installed

### ISSUE THREAD

**Issue by rbcrack** [MISP/MISP-maltego#47]
I have  installed MISP-Maltego locally  on Windows and Linux

Windows : ERROR: Cannot connect to MISP server. Please verify your MISP_Maltego.conf settings 

and

Linux - Error running local transform: java.io.IOException: Cannot run program "/usr/local/bin/dispatcher" (in directory "\home\MISP-maltego\src"): CreateProcess error=2, The system cannot find the file specified (from entity

I have my Maltego installed on Windows 10.

**Comment by rbcrack** [comment]
Another update I setup a fresh install on Kali with Maltego logged in as root.

After setting up the MISP-Maltego I am still getting error unable to connect with the API

**Comment by cvandeplas** [comment]
Can you explain how you installed MISP-Maltego on linux?
The error message gives the impression there is something wrong with the installation of canari3. (`/usr/local/bin/dispatcher` is a component of canari3)

**Comment by rbcrack** [comment]
> Can you explain how you installed MISP-Maltego on linux?
> The error message gives the impression there is something wrong with the installation of canari3. (`/usr/local/bin/dispatcher` is a component of canari3)

I followed this 

Download and install Maltego
Install using pip: sudo pip3 install MISP-maltego
Generate the Maltego bundle: canari create-profile MISP_maltego
Import this bundle in Maltego.
Open Maltego
Click on the home button (Maltego icon, top-left corner).
Click on 'Import'
Click on 'Import Configuration'.
Load the MISP_maltego.mtz file and follow the prompts.
Edit $HOME/.canari/MISP_maltego.conf and enter your misp_url and misp_key

**Comment by rbcrack** [comment]
I can confirm in Kali it installed smooth but Windows and Ubunt needed some extra work but got it to work but all three install are having issues connecting local MISP, I think something blocking on MISP side if you any inside, please help

**Comment by cvandeplas** [comment]
Something caused the package to point to `/usr/local/bin/dispatcher`.
Can you manually check and confirm that file is indeed NOT present?
Can you locate it somewhere else on your system?

**Comment by cvandeplas** [comment]
Closing considering the absence of news

**Comment by Cyb3rHunt3rz** [comment]
> I have installed MISP-Maltego locally on Windows and Linux
> 
> Windows : ERROR: Cannot connect to MISP server. Please verify your MISP_Maltego.conf settings
> 
> and
> 
> Linux - Error running local transform: java.io.IOException: Cannot run program "/usr/local/bin/dispatcher" (in directory "\home\MISP-maltego\src"): CreateProcess error=2, The system cannot find the file specified (from entity
> 
> I have my Maltego installed on Windows 10.

I have a question on installation on windows 10. How do you setup the installation phases exactly? cause I already download python 3.11 and pip. and then for the Canari, how to install it in windows? can you help me with that?
