### ISSUE TITLE
Transform Execution Failed

### ISSUE THREAD

**Issue by Pyth18** [MISP/MISP-maltego#48]
Hello, I am starting to use Maltego, and ATT & CK has caught my attention. I understand that I should not use any API or server for execution. (Leave blank space) However when I run against an email I get the following error.

![image](https://user-images.githubusercontent.com/74792993/105936244-ed33ab00-6018-11eb-8d3c-d1ba33471017.png)

It is worth mentioning that I have updated Maltego.

Thank you for your answer,

**Comment by cvandeplas** [comment]
Hi,

The ATT&CK specific transforms do not require a key/server, but the MISP specific ones do.
The transform you are trying is `Search in MISP` is clearly MISP specific.

My code didn't expect people to put a space in the url/key, so that explains why the error is not that intuitive.
I'll fix this to ensure a better error message.

**Comment by Pyth18** [comment]
Hi,

Thank you. This means that I must get an API from MISP. How can I do this? I have reviewed the GitHub project, however I cannot find any information on that.

Thanks for your help,

**Comment by cvandeplas** [comment]
The ATT&CK (to galaxy, to actor, to technique) transforms do not need
a MISP API
key, but the MISP-specific transforms do.
You can get an API key and url from a MISP Threat Sharing community to
access data. We do not host a sharing community ourselves, this is open
source "software" anyone can use to share "data".
Many communities exist, and as most of them are not advertised publicly you
might want to ask around you, your colleagues and the communities you are a
member of.

Some publicly advertised communities are listed here: https://www.misp-
project.org/communities/

Kind regards
Christophe
