### ISSUE TITLE
Cannot Connect to MISP server

### ISSUE THREAD

**Issue by RandyRandleman** [MISP/MISP-maltego#49]
Hi all, great tool! Looking forward to getting this up and running: 

Getting an error "cannot connect to the MISP server. Please verify your settings and ensure the MISP server is reachable from the internet." 

Our MISP is currently internal, and we can access it via Browser. I have the URI and the API Key generated from my account in here. Are there settings within MISP that potentially need to be changed in order to allow the API call? Or potentially a firewall port? 

Thanks again!

**Comment by JLT032** [comment]
similar issue here, it did work partially, now i get "502 bad gateway" , what's your status ?

tests with this line work fine

`curl --header "Authorization: <apikeyhere>" --header "Accept: application/json" --header "Content-Type: application/json" https://<misphost>.<domain>.<tld>/ `

**Comment by cvandeplas** [comment]
I understand you are using a proxy.
Can you see the `curl` request in the proxy logs?
Can you see the requests that come from the maltego client in the proxy logs (to the MISP instance)? 

If the requests reach the proxy that's a sign it is the proxy that is blocking the request.
If it does not reach the proxy, I expect maltego (or python) don't get the right parameters. I would then start sniffing on the endpoint where misp-maltego is installed, to see where the requests go to.

**Comment by cvandeplas** [comment]
See https://github.com/MISP/MISP-maltego/issues/52

It seems the pip package was missing a crucial fix.
You can install the latest version v1.4.7 from pip or download it directly from github.
