### ISSUE TITLE
different entities for actor, tool/malware, technique, ...

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP-maltego#5]
This makes the graphs more readable

**Comment by cvandeplas** [comment]
An alternative is to use the same Galaxy entity, but use a custom icon.

**Comment by cvandeplas** [comment]
The implemented way was by using the same icons as MISP.
This keeps uniformity, however virually it's a bit dark and might be less nice than the STIX icons.

![Screenshot](https://github.com/MISP/MISP-maltego/raw/master/doc/screenshot.png)

**Comment by adulau** [comment]
Maybe at some point, we should have a default set of icons for the MISP project in SVG and especially icons where the transparency can be consistently set.
