### ISSUE TITLE
affiliation facebook 

### ISSUE THREAD

**Issue by Dopravno** [MISP/MISP-maltego#50]
affiliation facebook Search tools are different than they should be
![1624896103964785258003152739915](https://user-images.githubusercontent.com/86616284/123667969-ee246f00-d83a-11eb-929b-28722e2ab857.jpg)

Other options should appear

It is supposed to appear

![Screenshot_٢٠٢١٠٦٢٨_١٧٤٧٢٥](https://user-images.githubusercontent.com/86616284/123668092-10b68800-d83b-11eb-9184-d6537fec8e7c.jpg)

**Comment by Dopravno** [comment]
Sorry for mistakes in English

**Comment by cvandeplas** [comment]
the toPersonFromProfile and toProfileImage are no transforms from MISP-maltego. 
Your issue will therefore not be linked to this project, but to the Maltego software instead.
