### ISSUE TITLE
port supported in URL in MISP_maltego.conf? 

### ISSUE THREAD

**Issue by netmg** [MISP/misp-maltego#52]
Hi - 

We are trying to run MISP-maltego via a local install, installed on each user's desktop alongside a Maltego client.

We are also running internal MISP, CTAS and ITDS instances (in case it matters - but I don't believe it does).

From the same desktop I've got MISP-maltego installed on, I can curl to the MISP server with the desired **url/port and key** and get a valid response.  

```
curl -v --header "Authorization: <misp_key_here>" --header "Accept: application/json" --header "Content-Type: application/json" https://<misp_fqdn_here>:<misp_port_here>/
```

However - when I configure ~/.canari/MISP_maltego.conf with the same values:

   ```
[MISP_maltego.local]
   
   misp_url = https://<misp_fqdn_here>:<misp_port_here>/
   misp_key = <misp_key_here>
```

I get the error:

    _ERROR: Cannot connect to MISP server. Please verify your MISP_Maltego.conf settings_

It makes me wonder if the port addition in misp_url (required in our environment) is supported by MISP-maltego?

Thanks in advance for any help/comments.

**Comment by github-germ** [comment]
+1

**Comment by cvandeplas** [comment]
The port should be supported, that is passed transparently to PyMISP.
Can you edit your `$HOME/.canari/MISP_maltego.conf` and set  `misp_debug = True`  
Then enable the debug console in Maltego and launch the transform again.

What is the output?

**Comment by netmg** [comment]
Thanks for your quick response Christophe, very much appreciated.

I'm relatively new to Maltego, so the simple request to 'enable the debug console' took a while - but I think this is what what requested, via Transforms -> Transform Manager -> To MISP Events (Local), selected it and toggled "Show debug info" to on.

Once that is done, I re-run the MISP-maltego local transform.  The result is this text in the debug window:

```
Loading Canari configuration file '/Users/----/.canari/canari.conf'
<MaltegoMessage><MaltegoTransformExceptionMessage><Exceptions><Exception>ERROR: Cannot connect to MISP server. Please verify your MISP_Maltego.conf settings.</Exception></Exceptions></MaltegoTransformExceptionMessage></MaltegoMessage>
```

**Comment by netmg** [comment]
I also confirmed (on the same maltego client we are running local MISP-maltego on) via certificate manager that our MISP server is listed there as trusted, and a test request from that UI specifying the server:port MISP is accessible on is successful.

Adding those details here in case it helps narrow down our search.

**Comment by cvandeplas** [comment]
Oh my, did you install misp-maltego using pip?  
Check out https://github.com/MISP/MISP-maltego/issues/44#issuecomment-736737692 
If that workaround works for you (it does for me on a clean install) I might have made a big mistake in the package. 
I'll rebuild a new pip package after you confirm.

**Comment by netmg** [comment]
I did indeed install via pip.   I also saw that post (44) and thought (?) I confirmed that the pip install I did pulled the updated/merged code but there didn’t appear to be a difference in them?

I will confirm when I’m back at my desk, I’m mobile now and do not have access to everything I need. I will let you know.

Thanks again for your prompt reply!

**Comment by netmg** [comment]
I pulled the updated source for util.py via [#44 ](https://github.com/MISP/MISP-maltego/issues/44#issuecomment-736737692) and replaced the one that pip installed.  **It works!**

This was the only change I see, on line 88:

`<             self.misp = PyMISP(url=misp_url, key=misp_key, ssl=misp_verify, debug=misp_debug, tool='misp_maltego', timeout=(2, 60))
`

to

`>             self.misp = PyMISP(misp_url, misp_key, misp_verify, 'json', misp_debug, tool='misp_maltego', timeout=(2, 60))
`

Thank you Christophe!

**Comment by cvandeplas** [comment]
Can you try again with pip install ? (first remove the package, then reinstall it)
I have just pushed version 1.4.7 that should contain the same (corrected) version as was present on the git repository.

**Comment by netmg** [comment]
It looks good now, thank you!  

I removed/re-installed MISP-maltego via pip3, and the change is present.  Everything is working as desired.

```
15  __version__ = '1.4.7'  # also update version in setup.py

88  self.misp = PyMISP(url=misp_url, key=misp_key, ssl=misp_verify, debug=misp_debug, tool='misp_maltego', timeout=(2, 60))
```

**Comment by cvandeplas** [comment]
excellent, thanks for testing
