### ISSUE TITLE
error: Setup script exited with error in safedexml setup command: use_2to3 is invalid.

### ISSUE THREAD

**Issue by Aledangelo** [MISP/misp-maltego#56]
I'm trying to install MISP-maltego with pip3 and with setup.py file, but in both case it returns me this error:

Collecting safedexml
  Using cached safedexml-0.5.1.tar.gz (24 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in safedexml setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by abraaraarif** [comment]
I am also getting this error, could anyone please tell me how to resolve this?
Thank you in advance!

**Comment by Aledangelo** [comment]
> I am also getting this error, could anyone please tell me how to resolve this?
> 
> Thank you in advance!

It could be a problem with Python version, but I'm not sure because i haven't tried

**Comment by abraaraarif** [comment]
Thank you for your reply, was able to solve this issue using an older version of python.!
