### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character 

### ISSUE THREAD

**Issue by WeaverHeavy** [MISP/MISP-maltego#9]
![image](https://user-images.githubusercontent.com/28227854/52279553-cbbaef80-2927-11e9-9fd0-721c4746162f.png)
every time I try to run the transform on a MISP event I end up getting this error, any idea what may be causing it?

**Comment by cvandeplas** [comment]
It seems your Maltego is using python2.7, and not python3.

- What is the version of Maltego?
- How did you install MISP-Maltego?  (and Canari3)

**Comment by WeaverHeavy** [comment]
Maltego version: 4.1.15
I followed the README:

`git clone https://github.com/MISP/MISP-maltego.git`
`cd MISP-maltego`
`sudo pip3 install .`
`canari create-profile MISP_maltego`

**Comment by WeaverHeavy** [comment]
Disregard, I think I have resolved the issue.
